### ISSUE TITLE
如何添加relu6

### ISSUE THREAD

**Issue by Wenboisstrong** [205418367/onnx2caffe#1]
我的mobilenet的激活函数 是relu6 怎么在pycaffe添加这个relu6支持呢,博主有没有什么经验可以分享下

**Comment by Wenboisstrong** [comment]
My activation function is rule6, do you have any suggestions to help me?

**Comment by 205418367** [comment]
caffe没有relu6层，如果想在onnx2caffe中添加relu6，首先要在caffe中添加relu6层

**Comment by 205418367** [comment]
把你的mobilenet模型发给我看看

**Comment by Wenboisstrong** [comment]
[segmodel.zip](https://github.com/205418367/onnx2caffe/files/4811521/segmodel.zip)
我的是tf的训练的mobilenet+deeplab3+模型 之前没怎么用过caffe 想请教下如果我现在想pycaffe 支持一些非官方的层是不是需要下载 编译 别人的非官方的caffe 然后 重新安装pycaffe 模块这样pycaffe 就可以支持一些层 在我的模型中 caffe 原生 的是并不支持 resize 上采样的。 我通过对照编写了protoxt 文件 想把 权重通过pycaffe 写入但是 好像 pycaffe 对有不支持的层的图文件无法打开。您有什么经验么。

**Comment by 205418367** [comment]
你需要在caffe中添加不支持的层，然后重新编译caffe。添加层分两种情况，使用gpu和不使用gpu，如果用到gpu则涉及到cuda编程，这是一个复杂的工作！不使用gpu就比较简单了，写一个hpp和cpp文件来实现你的层，然后放到指定位置就可以了。
